esphome:
  name: "cyclopi"
  friendly_name: "CycloPi"
  comment: "CycloPi Backlight"
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    then:
      - light.turn_on:
          id: backlight
          effect: "strobe"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:

globals:
  - id: light_mode
    type: int
    initial_value: "2"  # 0 = off, 1 = solid, 2 = strobe
  - id: light_brightness
    type: int
    restore_value: True
    initial_value: "255"  # full brightness 0-255

esp32_ble_server:
  manufacturer: "CycloPi"
  model: "Backlight"
  services:
    - uuid: "12345678-1234-5678-1234-56789abcdef0"
      advertise: true
      characteristics:
        # Light mode characteristic
        - id: light_mode_char
          uuid: "abcdef01-1234-5678-1234-56789abcdef0"
          description: "Light Mode: 0=Off,1=Solid,2=Effect"
          read: true
          write: true
          notify: true
          value:
            type: uint8_t
            data: 0
          descriptors:
            - uuid: 2901
              value: "Set light mode: 0=Off,1=Solid,2=Effect"
          on_write:
            then:
              - lambda: |-
                  uint8_t mode = x[0];
                  ESP_LOGD("ble", "Light mode written: %d", mode);
                  id(light_mode) = mode;
                  if (mode == 0) {
                    id(backlight).turn_off().perform();
                  } else if (mode == 1) {
                    id(backlight).turn_on().set_effect("strobe").perform();
                  } else if (mode == 2) {
                    id(backlight).turn_on().set_effect("None").set_brightness((float)id(light_brightness) / 255.0).perform();
                  }

        # Brightness characteristic
        - id: light_brightness_char
          uuid: "abcdef02-1234-5678-1234-56789abcdef0"
          description: "Backlight Brightness (0-255)"
          read: true
          write: true
          notify: true
          value:
            type: uint8_t
            data: 255
          descriptors:
            - uuid: 2901
              value: "Set light brightness 0-255"
          on_write:
            then:
              - lambda: |-
                  uint8_t b = x[0];
                  id(light_brightness) = b;
                  ESP_LOGD("ble", "Brightness written: %d", id(light_brightness));
                  if (id(light_mode) == 2) {
                    id(backlight).turn_on().set_brightness((float)b / 255.0).perform();
                  }

# Sync BLE characteristics every 5s
interval:
  - interval: 5s
    then:
      - ble_server.characteristic.set_value:
          id: light_mode_char
          value: !lambda "return std::vector<uint8_t>{ (uint8_t)id(light_mode) };"
      - ble_server.characteristic.notify:
          id: light_mode_char
      - ble_server.characteristic.set_value:
          id: light_brightness_char
          value: !lambda "return std::vector<uint8_t>{ (uint8_t)id(light_brightness) };"
      - ble_server.characteristic.notify:
          id: light_brightness_char

light:
  - platform: esp32_rmt_led_strip
    rgb_order: RGB
    chipset: ws2811
    id: backlight
    pin: GPIO14
    num_leds: 64
    # color_correct: [40%, 40%, 40%]
    effects:
      - strobe:
          name: 'strobe'
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 300ms
            - state: true
              brightness: 100%
              red: 100%
              green: 50%
              blue: 0%
              duration: 250ms
            - state: false
              duration: 150ms
